name: Manual Builds Custom

on: 
  workflow_dispatch:
  
    inputs:
      buildosflavor:
        description: 'centos7 / centos8 / fedora / ubuntu / debian'
        required: true
        type: choice
        options: ['centos7', 'centos8', 'fedora', 'ubuntu', 'debian']
        default: 'fedora'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    
    - name: Cleanup Old Docker images if any
      run:  docker system prune -af
      
    - name: Selecting build based on OS flavour
      run: |
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos7" ]]; then
            docker pull quay.io/gluster/centos7-gluster-build
            docker run --name container_gluster -v /build-out:/out quay.io/gluster/centos7-gluster-build
  
            fi
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos8" ]]; then
            docker pull quay.io/gluster/centos8-gluster-build
            docker run --name container_gluster -v /build-out:/out quay.io/gluster/centos8-gluster-build

            fi
            if [[ "${{ github.event.inputs.buildosflavor }}" == "fedora" ]]; then
            docker pull quay.io/gluster/fedora-gluster-build
            docker run --name container_gluster -v /build-out:/out quay.io/gluster/fedora-gluster-build

            fi
            if [[ "${{ github.event.inputs.buildosflavor }}" == "ubuntu" ]]; then
            docker pull quay.io/gluster/ubuntu-gluster-build
            docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out quay.io/gluster/ubuntu-gluster-build

            fi
            if [[ "${{ github.event.inputs.buildosflavor }}" == "debian" ]]; then
            docker pull quay.io/gluster/debian-gluster-build
            docker run --name container_gluster -v /build-out:/out quay.io/gluster/debian-gluster-build

            fi
