name: Nightly Build (centos7/quay)

on:
  schedule:
    - cron:  '30 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    - name: Pull Docker Image From Quay 
      run: docker pull quay.io/gluster/centos7-gluster-build
    - name: Running Build in Centos7 Container
      run: docker run --name container_gluster quay.io/gluster/centos7-gluster-build
    - name: Copy Artifactory to Host
      run: docker cp container_gluster:/github/glusterfs/extras/LinuxRPM .
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: LinuxRPM/*.rpm
          retention-days: 1
