name: Nightly Build (ubuntu/quay)

on:
  schedule:
  - cron:  '35 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    - name: Cleanup Old Docker images if any
      run:  docker system prune -af
    - name: Pull Docker Image from quay
      run:  docker pull quay.io/gluster/ubuntu-gluster-build
    - name: Running Build in ubuntu Container
      run:  docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out quay.io/gluster/ubuntu-gluster-build
    - name: Upload Artifactory
      uses: actions/upload-artifact@v4
      with:
          name: gluster-deb
          path: /build-out/*.*deb
          retention-days: 1
