name: Nightly Build (fedora/quay)

on:
  schedule:
  - cron:  '45 0 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    - name: Pull Docker Image From Quay 
      run: docker pull quay.io/gluster/fedora-gluster-build
    - name: Running Build in Fedora Container
      run: docker run --name container_gluster -v /build-out:/out quay.io/gluster/fedora-gluster-build
    - name: Upload Artifactory
      uses: actions/upload-artifact@v4
      with:
          name: gluster-rpms
          path: /build-out/*.rpm
          retention-days: 1
