name: Quay Monthly Trigger 

#Added monthly Cron for 14th of every month
on:
  schedule:
    - cron:  '0 0 15 * *'

jobs:
  run:
    name: Update a text file
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      # Add an update to repo file to trigger quay build...
      - run: echo "Quay Build is triggered on $(date)" >> ./Docker/monthly-trigger-log.txt

      # ...and then use the action as you would normally do
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'GitHub Actions Monthly Trigger'
          add: 'monthly-trigger-log.txt --force'
          cwd: '/Docker/'
          default_author: github_actions
